apiVersion: v1
kind: Service
metadata:
  name: simple-bysybox2
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: ClusterIP
  selector:
    app: trivial-go-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
